name: Monthly Twitter Sentiment Report

on:
  # first day of month @ 08:30 UTC
  schedule:
    - cron: '30 8 1 * *'
  workflow_dispatch:

jobs:
  build-report:
    runs-on: ubuntu-latest

    env:
      # Supabase
      SUPABASE_URL:          ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
      # Mailjet (kept, but unused unless SEND_EMAIL=true)
      MJ_API_KEY:            ${{ secrets.MJ_API_KEY }}
      MJ_API_SECRET:         ${{ secrets.MJ_API_SECRET }}
      MAIL_FROM:             ${{ vars.MAIL_FROM }}
      MAIL_TO:               ${{ vars.MAIL_TO }}
      # Email toggle (OFF by default)
      SEND_EMAIL:            "false"
      CI: true
      R_KEEP_PKG_SOURCE: no

    steps:
      - uses: actions/checkout@v4

      # System libraries (incl. GLPK for igraph/ggraph)
      - name: Install system libraries
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            ghostscript \
            libssl-dev libxml2-dev libcurl4-openssl-dev \
            libfontconfig1-dev libfreetype6-dev libharfbuzz-dev libfribidi-dev \
            libpng-dev libtiff5-dev libjpeg-dev libnss3 libxss1 \
            libglpk-dev

      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      # Headless Chrome for pagedown
      - name: Install headless Chrome
        id: chrome
        uses: browser-actions/setup-chrome@v2
        with:
          install-dependencies: true
          chrome-version: stable

      - name: Export CHROME_BIN
        run: echo "CHROME_BIN=${{ steps.chrome.outputs.chrome-path }}" >> "$GITHUB_ENV"

      - name: Run monthly sentiment script
        run: Rscript run_monthly_sentiment.R

      - name: Upload report artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: monthly-numeric-report
          path: |
            *.pdf
            *.html
          if-no-files-found: warn
